name: BlockRename
main: ru.cofob.BlockRename.BlockRename
version: 0.1.0
description: Block anvil renames
depend: [Vault]
authors: [cofob]
api-version: 1.13
commands:
  blockrename:
    usage: /blockrename - reloads config