name: BlockRename
main: com.cofob.BlockRename.BlockRename
version: 0.0.2
description: Block anvil renames
depend: []
authors: [cofob]
api-version: 1.13
commands:
  blockrename:
    usage: /blockrename - reloads config